// ========================================
// PRODUTOS - Dados e funções auxiliares
// ========================================

const products = [
	{
		id: 1,
		name: "Sony WH-1000XM5",
		slug: "sony-wh-1000xm5",
		price: 1499.9,
		originalPrice: 1999.9,
		discount: 25,
		image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&q=80",
		category: "Áudio",
		rating: 4.9,
		reviews: 847,
		inStock: true,
		featured: true,
		isNew: false,
		description:
			"O melhor fone com cancelamento de ruído do mercado. Drivers de 30mm, até 30 horas de bateria, conexão multipoint com 2 dispositivos simultâneos e dobráveis para transporte.",
		specifications: {
			brand: "Sony",
			model: "WH-1000XM5",
			driver: "30mm",
			connectivity: "Bluetooth 5.2 + P2 3,5mm",
			battery: "30 horas (ANC ligado)",
			weight: "250g",
			noise_cancelling: "ANC adaptativo",
		},
	},
	{
		id: 2,
		name: "Apple Watch Series 9 GPS 45mm",
		slug: "apple-watch-series-9-45mm",
		price: 3299.9,
		originalPrice: 4099.9,
		discount: 20,
		image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500&q=80",
		category: "Wearables",
		rating: 4.8,
		reviews: 512,
		inStock: true,
		featured: true,
		isNew: false,
		description:
			"Apple Watch com chip S9 SiP, tela Always-On Retina de 45mm, sensor de temperatura corporal, ECG, detecção de colisão e carga por USB-C.",
		specifications: {
			brand: "Apple",
			model: "Series 9 GPS",
			display: "Retina LTPO OLED 45mm",
			chip: "Apple S9 SiP",
			battery: "Até 18 horas",
			water_resistance: "WR50",
			sensors: "ECG, Oxímetro, Temp. corporal",
		},
	},
	{
		id: 3,
		name: "Samsung Galaxy S24 Ultra 256GB",
		slug: "samsung-galaxy-s24-ultra",
		price: 6799.9,
		originalPrice: 8499.9,
		discount: 20,
		image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500&q=80",
		category: "Smartphones",
		rating: 4.8,
		reviews: 634,
		inStock: true,
		featured: false,
		isNew: true,
		description:
			"Câmera de 200MP, chip Snapdragon 8 Gen 3, tela Dynamic AMOLED 2X de 6,8\" com 120Hz, S Pen inclusa e bateria de 5000mAh com carregamento de 45W.",
		specifications: {
			brand: "Samsung",
			model: "Galaxy S24 Ultra",
			display: '6.8" Dynamic AMOLED 2X 120Hz',
			processor: "Snapdragon 8 Gen 3",
			camera: "200MP + 12MP + 10MP + 50MP",
			battery: "5000mAh — carga 45W",
			storage: "256GB / 12GB RAM",
		},
	},
	{
		id: 4,
		name: "MacBook Air M2 13\" 256GB",
		slug: "macbook-air-m2-13",
		price: 9299.9,
		originalPrice: 11499.9,
		discount: 19,
		image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=500&q=80",
		category: "Computadores",
		rating: 4.9,
		reviews: 389,
		inStock: true,
		featured: true,
		isNew: false,
		description:
			"O notebook mais fino da Apple. Chip M2 com CPU 8 núcleos e GPU 8 núcleos, tela Liquid Retina de 13,6\", até 18h de bateria e design sem ventoinha.",
		specifications: {
			brand: "Apple",
			model: "MacBook Air M2",
			chip: "Apple M2 (8 núcleos CPU / 8 GPU)",
			display: "13.6\" Liquid Retina 2560x1664",
			memory: "8GB RAM unificada",
			storage: "256GB SSD",
			battery: "Até 18 horas",
		},
	},
	{
		id: 5,
		name: "Keychron Q3 Pro QMK/VIA",
		slug: "keychron-q3-pro",
		price: 849.9,
		originalPrice: 1199.9,
		discount: 29,
		image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500&q=80",
		category: "Periféricos",
		rating: 4.7,
		reviews: 291,
		inStock: true,
		featured: false,
		isNew: true,
		description:
			"Teclado mecânico TKL sem fio com conexão Bluetooth 5.1 e cabo USB-C. Estrutura em alumínio CNC, suporte QMK/VIA para programação total das teclas e switches Gateron G Pro Red.",
		specifications: {
			brand: "Keychron",
			model: "Q3 Pro",
			layout: "TKL (87 teclas) ABNT2",
			switches: "Gateron G Pro Red",
			connectivity: "Bluetooth 5.1 + USB-C",
			lighting: "RGB por tecla",
			body: "Alumínio CNC",
		},
	},
	{
		id: 6,
		name: "Logitech G Pro X Superlight 2",
		slug: "logitech-g-pro-x-superlight-2",
		price: 699.9,
		originalPrice: 999.9,
		discount: 30,
		image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=500&q=80",
		category: "Periféricos",
		rating: 4.8,
		reviews: 478,
		inStock: true,
		featured: false,
		isNew: false,
		description:
			"O mouse sem fio mais leve para gaming profissional. Sensor HERO 2 de 32.000 DPI, 95 horas de bateria, peso de apenas 60g e tecnologia LIGHTSPEED de 1ms de latência.",
		specifications: {
			brand: "Logitech",
			model: "G Pro X Superlight 2",
			sensor: "HERO 2 — 32.000 DPI",
			weight: "60g",
			battery: "95 horas",
			connectivity: "LIGHTSPEED 1ms + USB-C",
			buttons: "5 programáveis",
		},
	},
	{
		id: 7,
		name: "LG UltraGear 27GP850-B 27\" QHD 165Hz",
		slug: "lg-ultragear-27gp850",
		price: 2499.9,
		originalPrice: 3299.9,
		discount: 24,
		image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=500&q=80",
		category: "Monitores",
		rating: 4.8,
		reviews: 203,
		inStock: true,
		featured: true,
		isNew: false,
		description:
			"Monitor gamer QHD com painel Nano IPS de 1ms, 165Hz (OC até 180Hz), compatível com NVIDIA G-SYNC e AMD FreeSync Premium Pro, cobertura DCI-P3 98%.",
		specifications: {
			brand: "LG",
			model: "27GP850-B",
			display: "27\" Nano IPS QHD 2560x1440",
			refresh_rate: "165Hz (OC 180Hz)",
			response_time: "1ms GtG",
			hdr: "VESA DisplayHDR 400",
			color: "DCI-P3 98%",
		},
	},
	{
		id: 8,
		name: "GoPro HERO12 Black",
		slug: "gopro-hero12-black",
		price: 2199.9,
		originalPrice: 2999.9,
		discount: 27,
		image: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=500&q=80",
		category: "Fotografia",
		rating: 4.7,
		reviews: 176,
		inStock: true,
		featured: false,
		isNew: false,
		description:
			"Câmera de ação com vídeo 5.3K60 + 4K120, sensor 1/1.9\", estabilização HyperSmooth 6.0, resistente à água até 10m sem caixa e bateria 30% maior.",
		specifications: {
			brand: "GoPro",
			model: "HERO12 Black",
			video: "5.3K/60fps — 4K/120fps",
			photo: "27MP",
			stabilization: "HyperSmooth 6.0",
			waterproof: "Até 10m sem case",
			battery: "1720mAh",
		},
	},
	{
		id: 9,
		name: "Samsung 990 Pro SSD NVMe 2TB",
		slug: "samsung-990-pro-2tb",
		price: 649.9,
		originalPrice: 999.9,
		discount: 35,
		image: "https://images.unsplash.com/photo-1531492746076-161ca9bcad58?w=500&q=80",
		category: "Armazenamento",
		rating: 4.9,
		reviews: 521,
		inStock: true,
		featured: false,
		isNew: false,
		description:
			"SSD NVMe PCIe 4.0 de alto desempenho com leitura sequencial de até 7.450 MB/s e escrita de 6.900 MB/s. Ideal para jogos, edição 4K e workstations.",
		specifications: {
			brand: "Samsung",
			model: "990 Pro",
			capacity: "2TB",
			interface: "PCIe 4.0 NVMe M.2",
			read_speed: "7.450 MB/s",
			write_speed: "6.900 MB/s",
			endurance: "1.200 TBW",
		},
	},
	{
		id: 10,
		name: "JBL Charge 5",
		slug: "jbl-charge-5",
		price: 1099.9,
		originalPrice: 1499.9,
		discount: 27,
		image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500&q=80",
		category: "Áudio",
		rating: 4.7,
		reviews: 682,
		inStock: true,
		featured: true,
		isNew: false,
		description:
			"Caixa de som portátil com 40W RMS, bateria de 20 horas, à prova d'água IP67, carregamento de outros dispositivos via USB-A e tecnologia JBL PartyBoost.",
		specifications: {
			brand: "JBL",
			model: "Charge 5",
			power: "40W RMS",
			battery: "20 horas",
			waterproof: "IP67",
			connectivity: "Bluetooth 5.1",
			charging: "USB-C + saída USB-A",
		},
	},
	{
		id: 11,
		name: "Apple AirPods Pro 2ª Geração",
		slug: "airpods-pro-2",
		price: 1699.9,
		originalPrice: 2199.9,
		discount: 23,
		image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500&q=80",
		category: "Áudio",
		rating: 4.8,
		reviews: 934,
		inStock: true,
		featured: false,
		isNew: false,
		description:
			"ANC até 2x mais eficiente, áudio Adaptativo, Transparência adaptativa, chip H2, resistência IP54 e até 30 horas de autonomia total com o estojo de carregamento USB-C.",
		specifications: {
			brand: "Apple",
			model: "AirPods Pro 2ª Geração",
			chip: "Apple H2",
			anc: "Cancelamento de ruído ativo 2x",
			battery: "6h (earbuds) + 30h (estojo)",
			waterproof: "IP54",
			connectivity: "Bluetooth 5.3",
		},
	},
	{
		id: 12,
		name: "iPad Air M2 11\" Wi-Fi 128GB",
		slug: "ipad-air-m2-11",
		price: 5299.9,
		originalPrice: 6499.9,
		discount: 18,
		image: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500&q=80",
		category: "Tablets",
		rating: 4.9,
		reviews: 417,
		inStock: true,
		featured: true,
		isNew: true,
		description:
			"Chip M2 com CPU 8 núcleos e GPU 9 núcleos, tela Liquid Retina de 11\" com True Tone e P3 wide color, câmera traseira de 12MP e suporte a Apple Pencil Pro e Magic Keyboard.",
		specifications: {
			brand: "Apple",
			model: "iPad Air M2 11\"",
			chip: "Apple M2",
			display: "11\" Liquid Retina 2360x1640",
			storage: "128GB",
			camera: "12MP traseira / 12MP frontal",
			connectivity: "Wi-Fi 6E + Bluetooth 5.3",
		},
	},
];

// Funções auxiliares
function getProductById(id) {
	return products.find((p) => p.id === parseInt(id));
}

function getProductBySlug(slug) {
	return products.find((p) => p.slug === slug);
}

function getFeaturedProducts() {
	return products.filter((p) => p.featured);
}

function getProductsByCategory(category) {
	return products.filter((p) => p.category === category);
}

function getCategories() {
	return [...new Set(products.map((p) => p.category))];
}

function formatCurrency(value) {
	return new Intl.NumberFormat("pt-BR", {
		style: "currency",
		currency: "BRL",
	}).format(value);
}
